import { LessonCard } from "../../../types/curriculum";

export const forexCards: LessonCard[] = [
  {
    type: "visual_intro",
    title: "Forex Is a Quote Network, Not One Central Exchange",
    label: "Market Structure",
    visualKey: "forex-network-visual",
    body: "Forex is decentralized. You are not looking at one universal central exchange order book; you are looking at a feed generated by a network of providers, brokers, and aggregators.",
    context: {
      keyTerms: [
        { term: "Decentralized", definition: "A market with no single central location or exchange." },
        { term: "Liquidity Provider", definition: "Large banks and institutions that provide the underlying price quotes." },
        { term: "Broker / Aggregator", definition: "The entity that connects you to the liquidity network." },
        { term: "Quote Feed", definition: "The stream of prices shown on your chart." }
      ],
      whyThisMatters: "Retail learners often think there is one 'true' price. In Forex, the quote you see depends on your provider's network. Understanding this helps you focus on behavior over tiny price discrepancies.",
      realLifeExample: "Buying a currency at a local airport vs. an online bank. The underlying asset is the same, but the network and fees create different quotes.",
      commonMistake: "Thinking every chart for the same pair must look exactly the same at all times.",
      quickNote: "Forex is a network, not a building."
    }
  },
  {
    type: "visual_intro",
    title: "Bid, Ask, and Spread in Forex",
    label: "Quote Mechanics",
    visualKey: "forex-quote-panel-visual",
    body: "Forex is read through quoted bid/ask prices. Before reading candle movement, you must understand the cost of interaction: the spread.",
    context: {
      keyTerms: [
        { term: "Bid", definition: "The price where you can sell (hitting the buyer's level)." },
        { term: "Ask", definition: "The price where you can buy (hitting the seller's level)." },
        { term: "Spread", definition: "The difference between Bid and Ask, usually measured in pips." },
        { term: "Pip", definition: "The smallest price move in a Forex pair." }
      ],
      whyThisMatters: "The spread is your immediate cost. If the spread is wide, a move on the chart might not represent clean intent—it might just be a shift in the quote gap.",
      realLifeExample: "Buying a house at the listed price (Ask) but knowing you could only sell it immediately for less (Bid). The difference is the spread.",
      commonMistake: "Ignoring the spread when reading small candle movements.",
      quickNote: "You buy at the Ask and sell at the Bid."
    }
  },
  {
    type: "visual_intro",
    title: "Session Liquidity Changes the Quality of the Quote",
    label: "Liquidity Conditions",
    visualKey: "forex-session-liquidity-visual",
    body: "Forex market quality changes across sessions. Active overlaps provide the cleanest quotes; quiet sessions can be noisy and expensive.",
    context: {
      keyTerms: [
        { term: "Session Overlap", definition: "When two major markets (like London and NY) are open at once." },
        { term: "Market Quality", definition: "How reliable and clean the price movement feels based on liquidity." },
        { term: "Thin Market", definition: "A period with low volume where small orders can cause larger jumps." }
      ],
      whyThisMatters: "A candle in the middle of the London session has more 'weight' than the same sized candle during a quiet holiday or late-night period. Context changes the reading.",
      realLifeExample: "Driving in peak hour traffic (high liquidity, tight moves) vs. a quiet country road at night (low liquidity, sudden turns).",
      commonMistake: "Treating all sessions as equally valid for market reading.",
      quickNote: "Active sessions provide cleaner evidence."
    }
  },
  {
    type: "practice",
    title: "Forex Mini Drill: Clean Quote or Weak Reading?",
    label: "Practical Drill",
    visualKey: "forex-quote-quality-drill-visual",
    body: "You see EUR/USD move slightly upward on the chart. However, you notice the spread has widened and it is currently a low-liquidity quiet period. What is the disciplined Forex reading?",
    taskData: {
      type: "choice_block",
      question: "What is the disciplined Forex reading?",
      options: [
        { id: "A", text: "The candle moved up, so buyers are clearly in control.", isCorrect: false, feedback: "Not correct. In low-liquidity periods with wide spreads, small moves can happen without real buyer intent. The candle alone is not enough evidence." },
        { id: "B", text: "Treat the move carefully; the quote condition and liquidity are weak.", isCorrect: true, feedback: "Correct. Discipline requires checking the quote quality. If liquidity is low and spread is wide, a move is weak evidence." },
        { id: "C", text: "The widened spread is a buy signal because it shows urgency.", isCorrect: false, feedback: "Not correct. A widened spread is usually a sign of lower liquidity and higher risk, not a signal to act." },
        { id: "D", text: "Buy immediately because quiet sessions are easier to predict.", isCorrect: false, feedback: "Not correct. Quiet sessions are often noisier and more unpredictable due to thin order depth." }
      ]
    },
    context: {
      keyTerms: [
        { term: "Disciplined reading", definition: "Filtering market evidence based on liquidity and quote quality." },
        { term: "Weak condition", definition: "A state where chart movement is unreliable due to thin liquidity or wide spread." }
      ],
      whyThisMatters: "The 'Chart Guesser' reacts to every candle. The 'Market Reader' filters candles through quote quality and session context.",
      quickNote: "Filter the record through the condition."
    }
  }
];
