import { NavaMessage } from './types';

export const NAVA_MESSAGES: NavaMessage[] = [
  {
    id: 'onboarding_welcome',
    variant: 'welcome',
    trigger: 'dashboard_first_visit',
    title: 'Welcome to Lurnava',
    body: "I’m Nava, your Lurnava Guide. I’ll help you move through the learning path one step at a time.",
    ctaLabel: 'Start Foundations',
    ctaHref: '/course/module/0.1',
    attentionLevel: 'high',
    mode: 'cinematic_intro',
    pose: 'full_body',
    dismissible: true,
    showOnce: true,
    priority: 100,
  },
  {
    id: 'dashboard_returning',
    variant: 'welcome',
    trigger: 'dashboard_visit',
    title: 'Welcome back',
    body: 'You have progress in your current level. Let’s continue your learning path from where you left off.',
    ctaLabel: 'Continue Level 0',
    ctaHref: '/course',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetRoute: '/dashboard',
    targetSelector: '[data-nava-target="continue-learning-card"]',
    markerType: 'spark',
    sparkVariant: 'next',
    scrollToTarget: true,
    dismissible: true,
    showOnce: false,
    cooldownDays: 1,
    priority: 10,
    objective: {
      label: 'Continue current learning path',
      priority: 'primary'
    }
  },
  {
    id: 'course_level_2_intro',
    variant: 'tip',
    trigger: 'course_overview_visit',
    title: 'Level 2 Focus',
    body: 'In Level 2, we shift from basics to market structure. This concept helps you understand how price organizes itself.',
    attentionLevel: 'low',
    mode: 'side_tip',
    pose: 'bust_neutral',
    targetRoute: '/course',
    targetSelector: '[data-nava-target="level-card-2"]',
    markerType: 'spark',
    sparkVariant: 'available',
    dismissible: true,
    showOnce: true,
    priority: 5,
  },
  {
    id: 'module_intro_highlight',
    variant: 'tip',
    trigger: 'module_visit',
    title: 'Core Concept',
    body: 'This concept helps you understand the foundation of risk management. Take a moment to review the diagrams.',
    attentionLevel: 'low',
    mode: 'side_tip',
    pose: 'bust_neutral',
    targetRoute: '/course/module',
    targetSelector: '[data-nava-target="module-intro-card"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 5,
  },
  {
    id: 'practice_block_pulse',
    variant: 'tip',
    trigger: 'module_practice_visit',
    title: 'Practice This Concept',
    body: 'Try the Practice Block now. Applying this logic immediately is the best way to build chart-reading skill.',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetSelector: '[data-nava-target="practice-exercise-block"]',
    markerType: 'soft_pulse',
    scrollToTarget: true,
    dismissible: true,
    showOnce: false,
    cooldownDays: 3,
    priority: 5,
  },
  {
    id: 'test_result_review',
    variant: 'celebration',
    trigger: 'test_result_ready',
    title: 'Solid Result',
    body: 'Great work on the test. Your understanding of structure is improving. Let’s keep this momentum going!',
    attentionLevel: 'low',
    mode: 'celebration_moment',
    pose: 'celebration',
    targetSelector: '[data-nava-target="test-result-action"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 10,
  },
  {
    id: 'lab_intro_pulse',
    variant: 'tip',
    trigger: 'lab_visit',
    title: 'Start Practice',
    body: 'Ready to start? Use this button to begin your first chart-reading practice in the Lab.',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetRoute: '/lab',
    targetSelector: '[data-nava-target="practice-concept-cta"]',
    markerType: 'spark',
    sparkVariant: 'available',
    dismissible: true,
    showOnce: true,
    priority: 5,
    objective: {
      label: 'Complete your first Lab practice',
      priority: 'secondary'
    }
  },
  {
    id: 'journal_empty_state',
    variant: 'tip',
    trigger: 'journal_visit',
    title: 'Your Learning Path',
    body: 'This space tracks your development. As you save more notes, you can review your progress here.',
    attentionLevel: 'low',
    mode: 'side_tip',
    pose: 'avatar',
    targetRoute: '/journal',
    targetSelector: '[data-nava-target="saved-analysis-tab"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 5,
  },
  {
    id: 'locked_level_explanation',
    variant: 'locked',
    trigger: 'locked_level_attempt',
    title: 'Level Locked',
    body: 'To reach this level, you must first complete the knowledge test for the previous stage.',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetSelector: '[data-nava-target="gate-requirement-card"]',
    markerType: 'spark',
    sparkVariant: 'locked',
    dismissible: true,
    showOnce: false,
    cooldownDays: 0,
    priority: 20,
  }
];
