import { NavaMessage } from './types';

export const NAVA_MESSAGES: NavaMessage[] = [
  {
    id: 'onboarding_welcome',
    variant: 'welcome',
    trigger: 'dashboard_first_visit',
    title: 'Welcome to Lurnava',
    body: "I’m Nava, your Lurnava Guide. I’ll help you move through the learning path one step at a time.",
    ctaLabel: 'Start Foundations',
    ctaHref: '/course/module/0.1',
    attentionLevel: 'high',
    mode: 'cinematic_intro',
    pose: 'full_body',
    dismissible: true,
    showOnce: true,
    priority: 100,
  },
  {
    id: 'dashboard_returning_personalized',
    variant: 'welcome',
    trigger: 'personalized_next_action',
    title: 'Welcome back',
    body: 'Your next step is the Level {level} {type}. Continue there while the ideas are fresh.',
    ctaLabel: 'Continue Path',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetRoute: '/dashboard',
    targetSelector: '[data-nava-target="continue-learning-card"]',
    markerType: 'spark',
    sparkVariant: 'next',
    scrollToTarget: true,
    dismissible: true,
    showOnce: false,
    cooldownDays: 1,
    priority: 80,
    objective: {
      label: 'Continue current learning path',
      priority: 'primary'
    }
  },
  {
    id: 'level_0_tone_orientation',
    variant: 'tip',
    trigger: 'dashboard_visit',
    title: 'Focus on Basics',
    body: 'Start with foundations. You do not need to understand everything today.',
    attentionLevel: 'low',
    mode: 'side_tip',
    pose: 'bust_neutral',
    targetRoute: '/dashboard',
    dismissible: true,
    showOnce: true,
    priority: 30,
  },
  {
    id: 'level_2_tone_orientation',
    variant: 'tip',
    trigger: 'dashboard_visit',
    title: 'Visual Structure',
    body: 'Level 2 adds more visual structure. Move slowly and check the mission requirements before rushing.',
    attentionLevel: 'low',
    mode: 'side_tip',
    pose: 'bust_neutral',
    targetRoute: '/dashboard',
    dismissible: true,
    showOnce: true,
    priority: 30,
  },
  {
    id: 'test_review_needed_generic',
    variant: 'tip',
    trigger: 'test_review_needed',
    title: 'Review Useful',
    body: 'This test needs another review. Revisit the level material, then retry with a clearer structure.',
    attentionLevel: 'medium',
    mode: 'recovery_support',
    pose: 'empathy',
    targetSelector: '[data-nava-target="knowledge-test-launcher"]',
    markerType: 'spark',
    sparkVariant: 'review',
    dismissible: true,
    showOnce: false,
    priority: 60,
  },
  {
    id: 'mission_review_needed_generic',
    variant: 'tip',
    trigger: 'mission_review_needed',
    title: 'Mission Review',
    body: 'This mission needs another look. Review the requirement, then retry with a cleaner structure.',
    attentionLevel: 'medium',
    mode: 'recovery_support',
    pose: 'empathy',
    targetSelector: '[data-nava-target="chart-mission-launcher"]',
    markerType: 'spark',
    sparkVariant: 'review',
    dismissible: true,
    showOnce: false,
    priority: 60,
  },
  {
    id: 'journal_milestone_1',
    variant: 'celebration',
    trigger: 'journal_milestone',
    title: 'First Note Saved',
    body: 'First practice note saved. Good habit. Writing the reason helps make chart-reading clearer.',
    attentionLevel: 'medium',
    mode: 'celebration_moment',
    pose: 'celebration',
    targetSelector: '[data-nava-target="saved-analysis-tab"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 70,
  },
  {
    id: 'journal_milestone_3',
    variant: 'celebration',
    trigger: 'journal_milestone',
    title: 'Reasoning Progress',
    body: 'Three practice notes saved. You are building a useful record of your reasoning.',
    attentionLevel: 'medium',
    mode: 'celebration_moment',
    pose: 'celebration',
    targetSelector: '[data-nava-target="saved-analysis-tab"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 70,
  },
  {
    id: 'course_level_2_intro',
    variant: 'tip',
    trigger: 'module_visit', // Using generic trigger for legacy
    title: 'Level 2 Focus',
    body: 'In Level 2, we shift from basics to market structure. This concept helps you understand how price organizes itself.',
    attentionLevel: 'low',
    mode: 'side_tip',
    pose: 'bust_neutral',
    targetRoute: '/course',
    targetSelector: '[data-nava-target="level-card-2"]',
    markerType: 'spark',
    sparkVariant: 'available',
    dismissible: true,
    showOnce: true,
    priority: 5,
  },
  {
    id: 'module_intro_highlight',
    variant: 'tip',
    trigger: 'module_visit',
    title: 'Core Concept',
    body: 'This concept helps you understand the foundation of risk management. Take a moment to review the diagrams.',
    attentionLevel: 'low',
    mode: 'side_tip',
    pose: 'bust_neutral',
    targetRoute: '/course/module',
    targetSelector: '[data-nava-target="module-intro-card"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 5,
  },
  {
    id: 'practice_block_pulse',
    variant: 'tip',
    trigger: 'module_visit',
    title: 'Practice This Concept',
    body: 'Try the Practice Block now. Applying this logic immediately is the best way to build chart-reading skill.',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetSelector: '[data-nava-target="practice-exercise-block"]',
    markerType: 'soft_pulse',
    scrollToTarget: true,
    dismissible: true,
    showOnce: false,
    cooldownDays: 3,
    priority: 5,
  },
  {
    id: 'module_completion_next_lesson',
    variant: 'celebration',
    trigger: 'test_result_ready', // Using this to trigger after result
    title: 'Lesson Complete',
    body: "Good. This lesson is complete. Continue to the next step while the concept is still fresh.",
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'celebration',
    targetSelector: '[data-nava-target="next-lesson-cta"]',
    markerType: 'spark',
    sparkVariant: 'next',
    scrollToTarget: true,
    dismissible: true,
    showOnce: false,
    priority: 15,
  },
  {
    id: 'test_result_passed',
    variant: 'celebration',
    trigger: 'test_result_ready',
    title: 'Test Passed',
    body: 'Level Test passed. Continue while the concepts are still fresh.',
    ctaLabel: 'Continue Learning Path',
    attentionLevel: 'low',
    mode: 'celebration_moment',
    pose: 'celebration',
    targetSelector: '[data-nava-target="test-result-action"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 15,
  },
  {
    id: 'test_result_review_needed',
    variant: 'tip',
    trigger: 'test_result_ready',
    title: 'Review Useful',
    body: 'This result is useful. Review the weak areas, then come back with a clearer structure.',
    ctaLabel: 'Review / Retry',
    attentionLevel: 'medium',
    mode: 'recovery_support',
    pose: 'empathy',
    targetSelector: '[data-nava-target="test-result-action"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: false,
    priority: 15,
  },
  {
    id: 'knowledge_test_unlocked',
    variant: 'tip',
    trigger: 'test_result_ready',
    title: 'Test Ready',
    body: 'The Level Test is ready. It checks whether the key ideas are clear enough before the next stage.',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetSelector: '[data-nava-target="knowledge-test-launcher"]',
    markerType: 'spark',
    sparkVariant: 'available',
    scrollToTarget: true,
    dismissible: true,
    showOnce: false,
    priority: 10,
  },
  {
    id: 'lab_intro_pulse',
    variant: 'tip',
    trigger: 'module_visit',
    title: 'Start Practice',
    body: 'Ready to start? Use this button to begin your first chart-reading practice in the Lab.',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetRoute: '/lab',
    targetSelector: '[data-nava-target="practice-concept-cta"]',
    markerType: 'spark',
    sparkVariant: 'available',
    dismissible: true,
    showOnce: true,
    priority: 5,
    objective: {
      label: 'Complete your first Lab practice',
      priority: 'secondary'
    }
  },
  {
    id: 'journal_empty_state',
    variant: 'tip',
    trigger: 'module_visit',
    title: 'Your Learning Path',
    body: 'This space tracks your development. As you save more notes, you can review your progress here.',
    attentionLevel: 'low',
    mode: 'side_tip',
    pose: 'avatar',
    targetRoute: '/journal',
    targetSelector: '[data-nava-target="saved-analysis-tab"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 5,
  },
  {
    id: 'locked_level_explanation',
    variant: 'locked',
    trigger: 'test_result_ready',
    title: 'Level Locked',
    body: 'To reach this level, you must first complete the knowledge test for the previous stage.',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetSelector: '[data-nava-target="gate-requirement-card"]',
    markerType: 'spark',
    sparkVariant: 'locked',
    dismissible: true,
    showOnce: false,
    cooldownDays: 0,
    priority: 20,
  },
  {
    id: 'mission_launcher_tip',
    variant: 'tip',
    trigger: 'mission_result_ready',
    title: 'New Mission',
    body: 'This chart mission turns the lesson into a visual decision. Open it when you’re ready to apply the concept.',
    ctaLabel: 'Open Chart Mission',
    attentionLevel: 'medium',
    mode: 'directional_focus',
    pose: 'pointing',
    targetSelector: '[data-nava-target="chart-mission-launcher"]',
    markerType: 'spark',
    sparkVariant: 'available',
    scrollToTarget: true,
    dismissible: true,
    showOnce: false,
    priority: 10,
  },
  {
    id: 'mission_result_passed',
    variant: 'celebration',
    trigger: 'mission_result_ready',
    title: 'Mission Success',
    body: 'Good. You applied the visual logic and completed the mission. Continue while the chart idea is still fresh.',
    attentionLevel: 'low',
    mode: 'celebration_moment',
    pose: 'celebration',
    targetSelector: '[data-nava-target="mission-result-action"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: true,
    priority: 15,
  },
  {
    id: 'mission_result_review',
    variant: 'tip',
    trigger: 'mission_result_ready',
    title: 'Review Needed',
    body: 'This needs another look. Review the requirement, then retry with a clearer structure.',
    attentionLevel: 'medium',
    mode: 'recovery_support',
    pose: 'empathy',
    targetSelector: '[data-nava-target="mission-result-action"]',
    markerType: 'highlight_card',
    dismissible: true,
    showOnce: false,
    priority: 15,
  },
];
